name: Node.JS CD

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm publish --unsafe-perm --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}
